<!DOCTYPE html>
<html>
<head>
    <title>TrafficTelligence</title>
    <style>
        body {
            background-image: url('../static/background.jpg');
            background-size: cover;
            font-family: Arial, sans-serif;
            color: white;
            text-align: center;
            padding-top: 80px;
        }
        .form-box {
            background: rgba(0, 0, 0, 0.6);
            padding: 25px;
            margin: auto;
            width: 350px;
            border-radius: 15px;
        }
        input {
            width: 90%;
            padding: 10px;
            margin: 10px 0;
            border-radius: 8px;
            border: none;
        }
        button {
            padding: 10px 20px;
            margin: 10px 5px;
            border: none;
            border-radius: 10px;
            background-color: #28a745;
            color: white;
            font-weight: bold;
            cursor: pointer;
            transition: 0.3s;
        }
        button:hover {
            background-color: #218838;
        }
        .extra-buttons button {
            background-color: #007bff;
        }
        .extra-buttons button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="form-box">
        <h1>🚦 Traffic Volume Estimation</h1>
        <form method="POST" action="/predict" id="predictForm">
            <input type="number" name="day_of_week" placeholder="Day of Week (0=Mon)" required><br>
            <input type="number" name="hour" placeholder="Hour (0-23)" required><br>
            <input type="number" name="temperature" step="0.1" placeholder="Temperature °# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar username
buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
thanks_dev: # Replace with a single thanks.dev username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
